name: Deploy Next.js Frontend to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.2
        env:
          REPO_URL: https://github.com/${{ github.repository }}.git
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Updating system packages"
            sudo apt update -qq
            echo "Installing git and curl if needed"
            sudo apt install -y git curl
            echo "Navigating to app directory"
            cd ${{ secrets.APP_DIR }}
            echo "Cloning or pulling latest code"
            if [ ! -d .git ]; then
              git clone $REPO_URL .
            fi
            git pull origin main
            echo "Creating .env file"
            cat > .env <<EOF
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NODE_ENV=production
            EOF
            echo "Installing Node.js if needed"
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            echo "Installing PM2 if needed"
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi
            echo "Cleaning previous builds and dependencies"
            rm -rf node_modules .next
            echo "Installing dependencies"
            npm ci
            echo "Building Next.js app"
            npm run build
            echo "Pruning dev dependencies"
            npm prune --production
            echo "Restarting PM2 process"
            pm2 restart nextapp || pm2 start npm --name "nextapp" -- start
