name: Deploy Next.js Frontend to EC2
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Navigating to app directory"
            cd ${{ secrets.APP_DIR }}
            echo "Pulling latest code"
            git pull origin main
            echo "Creating .env file"
            cat > .env <<EOF
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NODE_ENV=production
            EOF
            echo "Cleaning previous builds and dependencies"
            rm -rf node_modules .next
            echo "Installing dependencies"
            npm ci
            echo "Building Next.js app"
            npm run build
            echo "Pruning dev dependencies"
            npm prune --production
            echo "Restarting PM2 process"
            pm2 restart nextapp || pm2 start npm --name "nextapp" -- start
