name: Simple Deploy to EC2

on:
  push:
    branches: [main]
  workflow_dispatch:  # For manual runs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          REPO_URL: ${{ github.repositoryUrl }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Quick setup if missing
            command -v node || { curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt install -y nodejs; }
            command -v git || sudo apt install -y git
            command -v pm2 || sudo npm i -g pm2

            # App dir
            cd ${{ secrets.APP_DIR }} || mkdir -p ${{ secrets.APP_DIR }} && cd ${{ secrets.APP_DIR }}
            [ ! -d .git ] && git clone $REPO_URL .

            # Update and build
            git pull origin main
            cat > .env << EOF
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NODE_ENV=production
            EOF
            rm -rf node_modules .next
            npm ci --production
            npm run build

            # Restart
            pm2 restart nextapp || pm2 start npm --name nextapp -- start
            pm2 save
